#!/usr/bin/env bash

# adapted from https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh

# Run this script in the top-level of your package directory
# (where the .cabal file is) to compile documentation and
# upload it to hackage.

set -e

dir=$(mktemp -d dist-docs.XXXXXX)
trap 'rm -rf "$dir"' EXIT

#cabal configure --builddir="$dir"
#cabal haddock --builddir="$dir" --for-hackage --haddock-option=--hyperlinked-source

cabal v2-haddock --builddir="$dir" --haddock-for-hackage --haddock-hyperlink-source

cabal upload  $1 -d $dir/*-docs.tar.gz
